spring:
  application:
    name: deep-research

research:
  async:
    max-pool-size: 10
    queue-capacity: 50
    task-timeout-minutes: 3

ai:
  config:
    - name: deepseek
      model: deepseek-v3
      baseUrl: https://api.deepseek.com
      apiKey: xxx
    - name: gpt
      model: gpt-5-mini
      baseUrl: https://api.openai.com
      apiKey: xxx
