spring:
  application:
    name: deep-research
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_deep_research?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

research:
  async:
    max-pool-size: 10
    queue-capacity: 50
    task-timeout-minutes: 3

ai:
  config:
    - name: deepseek
      model: deepseek-chat
      baseUrl: https://api.deepseek.com/v1
      apiKey: your_deepseek_api_key
    - name: gpt
      model: gpt-5-mini
      baseUrl: https://api.openai.com
      apiKey: your_openai_api_key
